### ISSUE TITLE
функция обновления списка еще непройденных нод

### ISSUE THREAD

**Issue by Dots109** [mai-806/Taxi.Graph#20]

**Comment by KochevDmitry** [comment]
### Алгоритм отправки координаты пользователя во время поездки

- Составление вектора Times, в котором каждый элемент - это время езды до соответствующей ноды ( по индексу )
- Сравнивание времени работы программы с первом элементом из Times, если время работы больше, то выведем координаты первой ноды
- Сравнивание будем делать раз в минуту ( можно поменять )
В функцию нужно передать все ноды маршрута, включая точку отправления и пункт назначения (важны координаты отправления в начале вектора, в алгоритме сразу присваивается время ноль этой ноде)
Функция завершается, когда достигли последней ноды.
