### ISSUE TITLE
преобразование координат в ноды и обратно

### ISSUE THREAD

**Issue by Dots109** [mai-806/Taxi.Graph#24]

**Comment by Dots109** [comment]
из номера ноды в координаты: через файл найти координаты ноды
обратно: понятно

**Comment by ktuzova** [comment]
напишу программу, которая считывает данные из файла, создает структуру для каждой строки файла и сохраняет ее в вектор. Затем программа запрашивает у пользователя координаты точки и находит ближайшую к ним вершину.

**Comment by ktuzova** [comment]
и наоборот с сашей напишем
