### ISSUE TITLE
файлы для загрузки в граф

### ISSUE THREAD

**Issue by Dots109** [mai-806/Taxi.Graph#25]

**Comment by cucurbitapepo** [comment]
обработал файл парса ОСМ карты. Разложил на два файла:
1 - номера нод (вершин графа) и их координаты
2 - рёбра и их свойства (точки начала и конца ребра, расстояние, максимальная разрешённая скорость, уровень пробок (0-10, рандомно), (bool)двустороннее движение, реальный адрес (если есть)
