### ISSUE TITLE
Алгоритм ценообразования

### ISSUE THREAD

**Issue by Dots109** [mai-806/Taxi.Graph#5]

**Comment by KochevDmitry** [comment]
### **Алгоритм ценообразования**
Разобьем нашу формулу цены на **_Тариф_** и **_Повышенный спрос_**:
_Тариф * Повышенный спрос = Цена_
### Тариф
В тарифе мы будем учитывать:
-  **цена за километр** - траты на обслуживание машины на один километр.
-  **цена за километр** - заработок таксиста в минуту ( средней заработок таксиста в час в Москве равен 675 рублям )
- **платная подача** - складывается из километров до пассажира и минут, которые потратит таксист для подъезда к пассажиру
Пока что не будем учитывать повышения цены из-за _детский кресел_, _перевозки животных_ и т.д.
<img width="302" alt="image" src="https://github.com/mai-806/Taxi.Graph/assets/65921394/ca1f6a89-2aa5-4564-b473-c75b42beefd8">

### **Повышенный спрос**
Повышенным спросом будем называть _**коэффициент**_, который включается, когда много людей заказывают такси и водителей не хватает. Этот коэффициент должен привлекать водителей ехать в ту область, где много заказов, а какую-то часть клиентов, наоборот, заставлять отказываться от такси и ехать на городском транспорте. Тем самым такси гарантируется каждому вызвавшему клиенту и сбоев не будет.
Обычно этот коэффициент зависит от многих факторов, включая **_погоду_**, **_сезонность_**, или, например, **_конец какого-нибудь концерта_** и т.д. Мы же будем учитывать **_час-пик_**, а именно утренний, вечерний, и ночной ( все едут с тусовок ).

<img width="452" alt="image" src="https://github.com/mai-806/Taxi.Graph/assets/65921394/74bb45cc-98f4-4909-857b-7c2f35f68f9e">



Также можно снижать стоимость, если есть возможность **_экономить_** время таксиста:
- Просить высадиться рядом с домом, не заезжая во двор 
- Сделать тариф "вместе"
- Снижать стоимость, если такси, которые вы вызвали, вот вот закончит заказ близко к вам 

и т.д.
Но это на будущее :)
